### 3.1.1 シグマ（∑）による総和の表記

In [1]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(np.sum(a))

15


In [2]:
import numpy as np

a = np.array([2, 1, 2, 1, 2])
b = np.array([1, 2, 1, 2, 1])

print(np.sum(a * b))

10


### 3.1.2 ネイピア数 e

In [3]:
import numpy as np

def get_exp(x): 
    return np.exp(x)

print(get_exp(1))

2.718281828459045


### 3.1.3 自然対数 log

In [4]:
import numpy as np

def get_log(x): 
    return np.log(x)

print(get_log(1))

0.0


## 3.2 線形代数

### 3.2.1 スカラー

In [5]:
a = 1
b = 1.2
c = -0.25
d = 1.2e5

### 3.2.2 ベクトル

In [6]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([-2.3, 0.25, -1.2, 1.8, 0.41])

### 3.2.3 行列

In [7]:
import numpy as np

a = np.array([[1, 2, 3], 
              [4, 5, 6]])
b = np.array([[0.21, 0.14],
              [-1.3, 0.81], 
              [0.12, -2.1]])

### 3.2.4 テンソル

In [8]:
import numpy as np

a = np.array([[[0, 1, 2, 3],
               [2, 3, 4, 5], 
               [4, 5, 6, 7]], # 最後に","が必要
              [[1, 2, 3, 4], 
               [3, 4, 5, 6], 
               [5, 6, 7, 8]]]) #(2, 3, 4)の3階テンソル

In [9]:
b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 
              16, 17, 18, 19, 20, 21, 22, 23, 24]) # 1階のテンソル（ベクトル）

b = b.reshape(4, 6) # 2階のテンソル（行列）
print(b)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [10]:
b = b.reshape(2, 3, 4) # 3階のテンソル
print(b)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [11]:
b = b.reshape(2, 2, 3, 2) # 4階のテンソル
print(b)

[[[[ 1  2]
   [ 3  4]
   [ 5  6]]

  [[ 7  8]
   [ 9 10]
   [11 12]]]


 [[[13 14]
   [15 16]
   [17 18]]

  [[19 20]
   [21 22]
   [23 24]]]]


In [12]:
c = np.array([[[1, 2, 3, 4], 
               [2, 0, 0, 0], 
               [3, 0, 0, 0]], 
             
              [[2, 0, 0, 0], 
               [0, 0, 0, 0], 
               [0, 0, 0, 0]]]) # (2, 3, 4)の3階テンソルを作成

c = c.transpose(0, 2, 1) # 軸の入れ替え
print(c)

[[[1 2 3]
  [2 0 0]
  [3 0 0]
  [4 0 0]]

 [[2 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [13]:
c = c.transpose(2, 0, 1)
print(c)

[[[1 2 3 4]
  [2 0 0 0]]

 [[2 0 0 0]
  [0 0 0 0]]

 [[3 0 0 0]
  [0 0 0 0]]]


In [14]:
c = c.transpose(1, 0, 2)
print(c)

[[[1 2 3 4]
  [2 0 0 0]
  [3 0 0 0]]

 [[2 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [15]:
import numpy as np

c = 2
a = np.array([[0, 1, 2], 
              [3, 4, 5], 
              [6, 7, 8]])

print(c * a)

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


### 3.2.6 要素毎の積

In [16]:
import numpy as np

a = np.array([[0, 1, 2], 
              [3, 4, 5],
              [6, 7, 8]])
b = np.array([[0, 1, 2], 
              [2, 0, 1], 
              [1, 2, 0]])

print(a * b)

[[ 0  1  4]
 [ 6  0  5]
 [ 6 14  0]]


In [17]:
print(a + b)

[[0 2 4]
 [5 4 6]
 [7 9 8]]


In [18]:
print(a - b)

[[0 0 0]
 [1 4 4]
 [5 5 8]]


In [19]:
print(a / (b + 1))

[[0.         0.5        0.66666667]
 [1.         4.         2.5       ]
 [3.         2.33333333 8.        ]]


In [20]:
print(a % (b + 1))

[[0 1 2]
 [0 0 1]
 [0 1 0]]


### 3.2.7 行列積

In [21]:
import numpy as np

a = np.array([[0, 1, 2], 
              [1, 2, 3]])
b = np.array([[2, 1], 
              [2, 1], 
              [2, 1]])

print(np.dot(a, b))

[[ 6  3]
 [12  6]]


In [22]:
import numpy as np

a = np.array([1, 2, 3]) # 行数1の行列として扱われる
b = np.array([[1, 2], 
              [1, 2], 
              [1, 2]])

print(np.dot(a, b))

[ 6 12]


### 3.2.8 行列の転置

In [23]:
import numpy as np

a = np.array([[1, 2, 3], 
              [4, 5, 6]])

print(a.T)

[[1 4]
 [2 5]
 [3 6]]


In [24]:
import numpy as np

a = np.array([[0, 1, 2], 
              [1, 2, 3]])
b = np.array([[0, 1, 2], 
              [1, 2, 3]])

print(np.dot(a, b.T)) # 天地によって行列席が可能, np.dot(a, b)はエラー

[[ 5  8]
 [ 8 14]]
